IF DB_ID('StudySubmitDb') IS NOT NULL
BEGIN
    ALTER DATABASE StudySubmitDb SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE StudySubmitDb;
END
GO

CREATE DATABASE StudySubmitDb;
GO
USE StudySubmitDb;
GO
